// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "typed-ember"
export const name = "glint2-vscode"
export const version = "1.0.2"
export const displayName = "Glint V2"
export const description = "Volar.js-powered Ember.js language server and TS Plugin for VS Code"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "glint2.restart-language-server"
  | "glint2.select-ember-tsc-source"

/**
 * Commands map registered by `typed-ember.glint2-vscode`
 */
export const commands = {
  /**
   * Glint V2: Restart Glint V2 Server
   * @value `glint2.restart-language-server`
   */
  restartLanguageServer: "glint2.restart-language-server",
  /**
   * Glint V2: Select Ember TSC Source
   * @value `glint2.select-ember-tsc-source`
   */
  selectEmberTscSource: "glint2.select-ember-tsc-source",
} satisfies Record<string, CommandKey>

/**
 * Type union of all languages
 */
export type LanguageKey =
  | "glimmer-js"
  | "glimmer-ts"

/**
 * Languages map registed by `typed-ember.glint2-vscode`
 */
export const languages = {
  glimmerJs: "glimmer-js",
  glimmerTs: "glimmer-ts",
} satisfies Record<string, LanguageKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "glint2.libraryPath"
  | "glint2.emberTscSource"
  | "glint2.trace.server"

export interface ConfigKeyTypeMap {
  "glint2.libraryPath": (string | undefined),
  "glint2.emberTscSource": ("auto" | "workspace" | "bundled"),
  "glint2.trace.server": ("off" | "messages" | "verbose"),
}

export interface ConfigShorthandMap {
  libraryPath: "glint2.libraryPath",
  emberTscSource: "glint2.emberTscSource",
  traceServer: "glint2.trace.server",
}

export interface ConfigShorthandTypeMap {
  libraryPath: (string | undefined),
  emberTscSource: ("auto" | "workspace" | "bundled"),
  traceServer: ("off" | "messages" | "verbose"),
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `typed-ember.glint2-vscode`
 */
export const configs = {
  /**
   *
   * @key `glint2.libraryPath`
   * @default `undefined`
   * @type `string`
   */
  libraryPath: {
    key: "glint2.libraryPath",
    default: undefined,
  } as ConfigItem<"glint2.libraryPath">,
  /**
   *
   * @key `glint2.emberTscSource`
   * @default `"auto"`
   * @type `string`
   */
  emberTscSource: {
    key: "glint2.emberTscSource",
    default: "auto",
  } as ConfigItem<"glint2.emberTscSource">,
  /**
   * Traces communication between VS Code and the Glint language server.
   * @key `glint2.trace.server`
   * @default `"off"`
   * @type `string`
   */
  traceServer: {
    key: "glint2.trace.server",
    default: "off",
  } as ConfigItem<"glint2.trace.server">,
}

export interface ScopedConfigKeyTypeMap {
  "libraryPath": (string | undefined),
  "emberTscSource": ("auto" | "workspace" | "bundled"),
  "trace.server": ("off" | "messages" | "verbose"),
}

export const scopedConfigs = {
  scope: "glint2",
  defaults: {
    "libraryPath": undefined,
    "emberTscSource": "auto",
    "trace.server": "off",
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "glint2": {
    "libraryPath": (string | undefined),
    "emberTscSource": ("auto" | "workspace" | "bundled"),
    "trace": {
      "server": ("off" | "messages" | "verbose"),
    },
  },
}

export interface NestedScopedConfigs {
  "libraryPath": (string | undefined),
  "emberTscSource": ("auto" | "workspace" | "bundled"),
  "trace": {
    "server": ("off" | "messages" | "verbose"),
  },
}

